// Hand-written screen (not generated by SquareLine Studio). Follows the
// same *_screen_init() / global lv_obj_t* pattern as ui_PlayerScreen.c so it
// fits the rest of this SquareLine-based UI.
//
// Widgets here are only created once, at ui_init() time. main/main.c's
// playlist_task populates/clears ui_PlaylistList and toggles
// ui_PlaylistStatusLabel each time the screen is opened; this file only
// builds the static skeleton.

#include "../ui.h"

void ui_PlaylistScreen_screen_init(void)
{
    ui_PlaylistScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PlaylistScreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_PlaylistScreen, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlaylistScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlaylistBackBtn = lv_btn_create(ui_PlaylistScreen);
    lv_obj_set_width(ui_PlaylistBackBtn, 40);
    lv_obj_set_height(ui_PlaylistBackBtn, 40);
    lv_obj_set_x(ui_PlaylistBackBtn, 10);
    lv_obj_set_y(ui_PlaylistBackBtn, 10);
    lv_obj_set_style_radius(ui_PlaylistBackBtn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * back_icon = lv_label_create(ui_PlaylistBackBtn);
    lv_label_set_text(back_icon, LV_SYMBOL_LEFT);
    lv_obj_center(back_icon);

    ui_PlaylistTitle = lv_label_create(ui_PlaylistScreen);
    lv_obj_set_width(ui_PlaylistTitle, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_PlaylistTitle, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_PlaylistTitle, 0);
    lv_obj_set_y(ui_PlaylistTitle, 18);
    lv_obj_set_align(ui_PlaylistTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_PlaylistTitle, "Playlists");
    lv_obj_set_style_text_font(ui_PlaylistTitle, &lv_font_es_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PlaylistTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlaylistStatusLabel = lv_label_create(ui_PlaylistScreen);
    lv_obj_set_width(ui_PlaylistStatusLabel, 440);
    lv_obj_set_height(ui_PlaylistStatusLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_PlaylistStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PlaylistStatusLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_align(ui_PlaylistStatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PlaylistStatusLabel, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_PlaylistStatusLabel, "");
    lv_obj_add_flag(ui_PlaylistStatusLabel, LV_OBJ_FLAG_HIDDEN);

    ui_PlaylistList = lv_list_create(ui_PlaylistScreen);
    lv_obj_set_width(ui_PlaylistList, 460);
    lv_obj_set_height(ui_PlaylistList, 250);
    lv_obj_set_x(ui_PlaylistList, 0);
    lv_obj_set_y(ui_PlaylistList, -10);
    lv_obj_set_align(ui_PlaylistList, LV_ALIGN_BOTTOM_MID);

    lv_obj_add_event_cb(ui_PlaylistBackBtn, ui_event_PlaylistBackBtn, LV_EVENT_ALL, NULL);
}
