// Hand-written screen (not generated by SquareLine Studio), same pattern as
// ui_PlaylistScreen.c/ui_PlayerScreen.c's ui_DeviceModal: dark palette,
// widgets built once at ui_init() time. search_screen.c's search_task
// populates/clears ui_SearchResultList and toggles ui_SearchStatusLabel; the
// query textarea/keyboard are driven by ui_events.c (openSearchFn/
// searchSubmitFn/searchBackFn).
//
// Layout (480x320 landscape):
//   top row: back button + query textarea
//   below:   status label (hidden unless loading/error/empty), OR the
//            results list - both occupy the same region since only one of
//            {keyboard, results list} is ever visible at a time (see
//            openSearchFn/searchSubmitFn).
//   bottom:  on-screen keyboard (lv_keyboard bound to ui_SearchInput),
//            hidden once a query is submitted, shown again on re-open.

#include "../ui.h"

void ui_SearchScreen_screen_init(void)
{
    ui_SearchScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SearchScreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_SearchScreen, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SearchScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SearchBackBtn = lv_btn_create(ui_SearchScreen);
    lv_obj_set_width(ui_SearchBackBtn, 40);
    lv_obj_set_height(ui_SearchBackBtn, 40);
    lv_obj_set_x(ui_SearchBackBtn, 10);
    lv_obj_set_y(ui_SearchBackBtn, 10);
    lv_obj_set_style_radius(ui_SearchBackBtn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * back_icon = lv_label_create(ui_SearchBackBtn);
    lv_label_set_text(back_icon, LV_SYMBOL_LEFT);
    lv_obj_center(back_icon);

    ui_SearchInput = lv_textarea_create(ui_SearchScreen);
    lv_textarea_set_one_line(ui_SearchInput, true);
    lv_textarea_set_placeholder_text(ui_SearchInput, "Buscar canción...");
    lv_obj_set_width(ui_SearchInput, 380);
    lv_obj_set_height(ui_SearchInput, 40);
    lv_obj_set_x(ui_SearchInput, -10);
    lv_obj_set_y(ui_SearchInput, 10);
    lv_obj_set_align(ui_SearchInput, LV_ALIGN_TOP_RIGHT);

    ui_SearchStatusLabel = lv_label_create(ui_SearchScreen);
    lv_obj_set_width(ui_SearchStatusLabel, 440);
    lv_obj_set_height(ui_SearchStatusLabel, LV_SIZE_CONTENT);
    lv_obj_set_y(ui_SearchStatusLabel, 70);
    lv_obj_set_align(ui_SearchStatusLabel, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_SearchStatusLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_align(ui_SearchStatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SearchStatusLabel, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_SearchStatusLabel, "");
    lv_obj_add_flag(ui_SearchStatusLabel, LV_OBJ_FLAG_HIDDEN);

    ui_SearchResultList = lv_list_create(ui_SearchScreen);
    lv_obj_set_width(ui_SearchResultList, 460);
    lv_obj_set_height(ui_SearchResultList, 240);
    lv_obj_set_y(ui_SearchResultList, 60);
    lv_obj_set_align(ui_SearchResultList, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_SearchResultList, LV_OBJ_FLAG_HIDDEN);

    // Bound to ui_SearchInput: typing focuses it automatically once tapped,
    // but it's also shown by default right away since this screen only ever
    // exists to type a query. Hidden once searchSubmitFn hands the query off
    // to search_task, shown again next time openSearchFn resets the screen.
    ui_SearchKeyboard = lv_keyboard_create(ui_SearchScreen);
    lv_keyboard_set_textarea(ui_SearchKeyboard, ui_SearchInput);
    lv_obj_set_size(ui_SearchKeyboard, 480, 190);
    lv_obj_align(ui_SearchKeyboard, LV_ALIGN_BOTTOM_MID, 0, 0);

    lv_obj_add_event_cb(ui_SearchBackBtn, ui_event_SearchBackBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SearchKeyboard, ui_event_SearchKeyboard, LV_EVENT_ALL, NULL);
}
