// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Spotify

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProgressBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_ProgressBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_ProgressBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ProgressBar, 400);
    lv_obj_set_height(ui_ProgressBar, 12);
    lv_obj_set_x(ui_ProgressBar, -6);
    lv_obj_set_y(ui_ProgressBar, 25);
    lv_obj_set_align(ui_ProgressBar, LV_ALIGN_CENTER);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 400);
    lv_obj_set_height(ui_Container1, 75);
    lv_obj_set_x(ui_Container1, -6);
    lv_obj_set_y(ui_Container1, 88);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x319A07), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrevBtn = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_PrevBtn, 70);
    lv_obj_set_height(ui_PrevBtn, 70);
    lv_obj_set_x(ui_PrevBtn, -123);
    lv_obj_set_y(ui_PrevBtn, 1);
    lv_obj_set_align(ui_PrevBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrevBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrevBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrevBtn, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PauseUnpauseBtn = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_PauseUnpauseBtn, 70);
    lv_obj_set_height(ui_PauseUnpauseBtn, 70);
    lv_obj_set_x(ui_PauseUnpauseBtn, 0);
    lv_obj_set_y(ui_PauseUnpauseBtn, 1);
    lv_obj_set_align(ui_PauseUnpauseBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PauseUnpauseBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PauseUnpauseBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PauseUnpauseBtn, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextBtn = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_NextBtn, 70);
    lv_obj_set_height(ui_NextBtn, 70);
    lv_obj_set_x(ui_NextBtn, 124);
    lv_obj_set_y(ui_NextBtn, 1);
    lv_obj_set_align(ui_NextBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NextBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NextBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NextBtn, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Track = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Track, 400);
    lv_obj_set_height(ui_Track, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Track, -6);
    lv_obj_set_y(ui_Track, -32);
    lv_obj_set_align(ui_Track, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Track, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_style_text_font(ui_Track, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ProgressBar, ui_event_ProgressBar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrevBtn, ui_event_PrevBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PauseUnpauseBtn, ui_event_PauseUnpauseBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextBtn, ui_event_NextBtn, LV_EVENT_ALL, NULL);

}
