// Hand-written screen (not generated by SquareLine Studio), same pattern as
// ui_SearchScreen.c: dark palette, widgets built once at ui_init() time.
// Shown at boot when there's no working stored Wi-Fi (main.c, wifi_screen.c,
// ANALYSIS.md 1.24/3.8) - no "back" target, network is mandatory here.
//
// Two sub-views, never both visible (same trick as ui_SearchScreen's list
// vs. keyboard): AP list (ui_WifiList + status, repopulated by
// wifi_screen_run_until_connected() on every scan) vs. password entry
// (ui_WifiPasswordBackBtn/Input/ui_WifiKeyboard, shown only for secured
// taps).

#include "../ui.h"

void ui_WifiScreen_screen_init(void)
{
    ui_WifiScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WifiScreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_WifiScreen, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiTitle = lv_label_create(ui_WifiScreen);
    lv_obj_set_width(ui_WifiTitle, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_WifiTitle, LV_SIZE_CONTENT);
    lv_obj_set_y(ui_WifiTitle, 14);
    lv_obj_set_align(ui_WifiTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WifiTitle, "Conectar a Wi-Fi");
    lv_obj_set_style_text_font(ui_WifiTitle, &lv_font_es_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WifiTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiStatusLabel = lv_label_create(ui_WifiScreen);
    lv_obj_set_width(ui_WifiStatusLabel, 440);
    lv_obj_set_height(ui_WifiStatusLabel, LV_SIZE_CONTENT);
    lv_obj_set_y(ui_WifiStatusLabel, 44);
    lv_obj_set_align(ui_WifiStatusLabel, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_WifiStatusLabel, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_align(ui_WifiStatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_WifiStatusLabel, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_WifiStatusLabel, "");
    lv_obj_add_flag(ui_WifiStatusLabel, LV_OBJ_FLAG_HIDDEN);

    ui_WifiList = lv_list_create(ui_WifiScreen);
    lv_obj_set_width(ui_WifiList, 460);
    lv_obj_set_height(ui_WifiList, 230);
    lv_obj_set_y(ui_WifiList, 70);
    lv_obj_set_align(ui_WifiList, LV_ALIGN_TOP_MID);

    ui_WifiPasswordBackBtn = lv_btn_create(ui_WifiScreen);
    lv_obj_set_width(ui_WifiPasswordBackBtn, 40);
    lv_obj_set_height(ui_WifiPasswordBackBtn, 40);
    lv_obj_set_x(ui_WifiPasswordBackBtn, 10);
    lv_obj_set_y(ui_WifiPasswordBackBtn, 10);
    lv_obj_set_style_radius(ui_WifiPasswordBackBtn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_WifiPasswordBackBtn, LV_OBJ_FLAG_HIDDEN);

    lv_obj_t * back_icon = lv_label_create(ui_WifiPasswordBackBtn);
    lv_label_set_text(back_icon, LV_SYMBOL_LEFT);
    lv_obj_center(back_icon);

    ui_WifiPasswordInput = lv_textarea_create(ui_WifiScreen);
    lv_textarea_set_one_line(ui_WifiPasswordInput, true);
    lv_textarea_set_password_mode(ui_WifiPasswordInput, true);
    lv_textarea_set_placeholder_text(ui_WifiPasswordInput, "Contraseña de red...");
    lv_obj_set_width(ui_WifiPasswordInput, 380);
    lv_obj_set_height(ui_WifiPasswordInput, 40);
    lv_obj_set_x(ui_WifiPasswordInput, -10);
    lv_obj_set_y(ui_WifiPasswordInput, 10);
    lv_obj_set_align(ui_WifiPasswordInput, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_WifiPasswordInput, LV_OBJ_FLAG_HIDDEN);

    ui_WifiKeyboard = lv_keyboard_create(ui_WifiScreen);
    lv_keyboard_set_textarea(ui_WifiKeyboard, ui_WifiPasswordInput);
    lv_obj_set_size(ui_WifiKeyboard, 480, 190);
    lv_obj_align(ui_WifiKeyboard, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_obj_add_flag(ui_WifiKeyboard, LV_OBJ_FLAG_HIDDEN);

    lv_obj_add_event_cb(ui_WifiPasswordBackBtn, ui_event_WifiPasswordBackBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiKeyboard, ui_event_WifiKeyboard, LV_EVENT_ALL, NULL);
}
