// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Spotify

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_PlayerScreen
void ui_PlayerScreen_screen_init(void);
lv_obj_t * ui_PlayerScreen;
void ui_event_ProgressBar(lv_event_t * e);
lv_obj_t * ui_ProgressBar;
lv_obj_t * ui_Container1;
void ui_event_PrevBtn(lv_event_t * e);
lv_obj_t * ui_PrevBtn;
void ui_event_PauseUnpauseBtn(lv_event_t * e);
lv_obj_t * ui_PauseUnpauseBtn;
void ui_event_NextBtn(lv_event_t * e);
lv_obj_t * ui_NextBtn;
lv_obj_t * ui_Track;
lv_obj_t * ui_Artists;
lv_obj_t * ui_CoverContainer;
lv_obj_t * ui_CoverImage;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ProgressBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        int value = *(int *)lv_event_get_param(e);
        _ui_bar_set_property(ui_ProgressBar, _UI_BAR_PROPERTY_VALUE_WITH_ANIM, value);
    }
}

void ui_event_PrevBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        prevFn(e);
    }
}

void ui_event_PauseUnpauseBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        pauseUnpauseFn(e);
    }
}

void ui_event_NextBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        nextFn(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_PlayerScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_PlayerScreen);
}
