// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Spotify

#ifndef _SQUARELINE_SPOTIFY_UI_H
#define _SQUARELINE_SPOTIFY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_ProgressBar(lv_event_t * e);
extern lv_obj_t * ui_ProgressBar;
extern lv_obj_t * ui_Container1;
void ui_event_PrevBtn(lv_event_t * e);
extern lv_obj_t * ui_PrevBtn;
void ui_event_PauseUnpauseBtn(lv_event_t * e);
extern lv_obj_t * ui_PauseUnpauseBtn;
void ui_event_NextBtn(lv_event_t * e);
extern lv_obj_t * ui_NextBtn;
extern lv_obj_t * ui_Track;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
