// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Spotify

#include "ui.h"
#include "spotify_client.h"

extern esp_spotify_client_handle_t client;

void prevFn(lv_event_t * e)
{
	player_dispatch_event(client, DO_PREVIOUS_EVENT);
}

void pauseUnpauseFn(lv_event_t * e)
{
	player_dispatch_event(client, PAUSE_UNPAUSE_EVENT);
}

void nextFn(lv_event_t * e)
{
	player_dispatch_event(client, DO_NEXT_EVENT);
}
