// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Spotify

#include "ui.h"
#include "spotify_client.h"

void prevFn(lv_event_t * e)
{
	spotify_dispatch_event(DO_PREVIOUS_EVENT);
}

void pauseUnpauseFn(lv_event_t * e)
{
	spotify_dispatch_event(PAUSE_UNPAUSE_EVENT);
}

void nextFn(lv_event_t * e)
{
	spotify_dispatch_event(DO_NEXT_EVENT);
}
