// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Spotify

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void prevFn(lv_event_t * e);
void pauseUnpauseFn(lv_event_t * e);
void nextFn(lv_event_t * e);
void openPlaylistsFn(lv_event_t * e);
void playlistBackFn(lv_event_t * e);
void volumeSliderChangedFn(lv_event_t * e);
void seekSliderChangedFn(lv_event_t * e);
void openDevicesFn(lv_event_t * e);
void closeDevicesFn(lv_event_t * e);
void openSearchFn(lv_event_t * e);
void searchSubmitFn(lv_event_t * e);
void searchBackFn(lv_event_t * e);
void wifiPasswordSubmitFn(lv_event_t * e);
void wifiPasswordBackFn(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
